#! /bin/sh

#
# Convenient script to create and configure eclipse workspace
#

if [ ! -d .metadata ] ; then 

  # configure xml, html, and javascript see corporate pom for detail

  mvn validate -Pconfigure-workspace -N $*
  
else

  echo .metadata directory already exists. 

fi
  
  
mvn eclipse:eclipse  -DdownloadSources=true $*
